fix: null exception when video libray change tracker is null
<FetchVideosCancelableAsync>d__61.MoveNext ()
System.ArgumentNullException: Value cannot be null. Parameter name: source